### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by MainasuK** [TwidereProject/TwidereX-iOS#139]
In the last few months, the app migrates lots of UI codes from UIKit to SwiftUI. The final goal for the app is to use UIKit to construct the skeleton and SwiftUI to make the UI components. But the cost is slow layout performance and causes the scrolling jump or lag. Also, there are tons of missing features for Twitter & Mastodon. Due to Twitter's recent API changes. We have to remove some features like the home timeline and mentions timeline. So the app has to focus on the Mastodon features in the future. 

#### Roadmap
- [x] Performance improvement: Plain object first. Only using the DB for data consistency and history.
- [ ] Timeline UX improve: unread indicator, e.t.c
- [ ] Theme: Different theme appearance
- [ ] Bookmark: Mastodon bookmark supports
- [ ] Schedule post: Publish the post in the schedule on Mastodon
- [ ] Metrics: App usage metric
- [ ] Profile edit: Mastodon profile info edit support
- [ ] Link preview: Preview the link via OpenGraph or API meta
- [ ] Inline translation: Display translation without opening the modal 
- [ ] Multi-column improvement: Create the new column on the next via the menu action
- [ ] Other issues listed in the repo
- [ ] Other features request

#### Milestone
This project is maintained by me. But I'm not fully on this. So I cannot give any promise about the release deadline. The tech stack used for this project is shared across multiple projects. The good news is some latest SDK features will be used but the minimal OS-supporting version also update. Therefore the app will not be a stable client in general.

#### Contribution
For the outside contributor who wants folk and build the app. Please open a ticket or reply to this issue. The `TwitterSDK` is a private package now. Please contact me for permission if you want to contribute.
